export type Property = {
  id: string;
  slug: string;
  title: string;
  type: 'sale' | 'rent' | 'off-plan' | 'land';
  price: number;
  priceSuffix?: string;
  priceCurrency?: 'KES' | 'USD';
  priceLabel?: string;
  bedrooms: number;
  bathrooms: number;
  location: string;
  area: string;
  description: string;
  features: string[];
  amenities: string[];
  plotSize?: string;
  paymentPlan?: string;
  completionDate?: string;
  images: string[];
  badge?: string;
  isFeatured?: boolean;
  isMortgageAvailable?: boolean;
};

export const properties: Property[] = [
  {
    id: '1',
    slug: '3br-bungalow-kihara-road',
    title: 'Modern 3BR Bungalow',
    type: 'sale',
    price: 13900000,
    bedrooms: 3,
    bathrooms: 3,
    location: 'Kihara Road, Kiambu',
    area: 'Kiambu',
    description: 'Beautiful 3-bedroom bungalow located on Kihara Road, featuring a gated community setup and Domestic Staff Quarters (DSQ).',
    features: ['Master Ensuite', 'Spacious Lounge', 'Dining Area', 'DSQ'],
    amenities: ['Gated Community', '24/7 Security', 'Ample Parking', 'Water Storage'],
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80'],
    badge: 'GATED COMMUNITY',
    isFeatured: true,
  },
  {
    id: '2',
    slug: '3br-apartment-thindigua',
    title: 'Spacious 3BR Apartment',
    type: 'rent',
    price: 75000,
    priceSuffix: '/mo',
    bedrooms: 3,
    bathrooms: 2,
    location: 'Thindigua, Kiambu Road',
    area: 'Thindigua',
    description: 'Premium 3-bedroom apartment along Kiambu Road with modern finishes and excellent natural light.',
    features: ['Modern Kitchen', 'Balcony', 'Laundry Area'],
    amenities: ['Backup Generator', 'High-Speed Lifts', 'Borehole', 'Gym'],
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80'],
  },
  {
    id: '3',
    slug: '2br-apartment-thindigua',
    title: 'Cozy 2BR Apartment',
    type: 'rent',
    price: 55000,
    priceSuffix: '/mo',
    bedrooms: 2,
    bathrooms: 2,
    location: 'Thindigua, Kiambu Road',
    area: 'Thindigua',
    description: 'Well-lit 2-bedroom apartment in a secure neighborhood, perfect for young professionals.',
    features: ['Ensuite Master', 'Open Plan Kitchen', 'Large Windows'],
    amenities: ['Secure Parking', 'CCTV', 'Borehole'],
    images: ['https://images.unsplash.com/photo-1502672260266-1c1de2d93688?w=800&q=80'],
  },
  {
    id: '4',
    slug: '4br-maisonette-ruiru-mugutha',
    title: 'Luxurious 4BR Maisonette',
    type: 'sale',
    price: 16000000,
    bedrooms: 4,
    bathrooms: 4,
    location: 'Mugutha, Ruiru',
    area: 'Ruiru',
    description: 'Executive 4-bedroom maisonette available for Ksh 16M cash or Ksh 17M mortgage.',
    features: ['All Ensuite', 'Family Room', 'Spacious Garden'],
    amenities: ['Gated Community', 'Paved Driveway', 'Electric Fence'],
    images: ['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80'],
    isMortgageAvailable: true,
    isFeatured: true,
  },
  {
    id: '5',
    slug: '4br-mansion-ruiru-mugutha',
    title: 'Premium 4BR Mansion',
    type: 'sale',
    price: 28000000,
    bedrooms: 4,
    bathrooms: 5,
    location: 'Mugutha, Ruiru',
    area: 'Ruiru',
    description: 'Elegant 4-bedroom mansion located just 500m from Thika Road with top-tier finishes.',
    features: ['High Ceilings', 'Custom Kitchen', 'Walk-in Closets'],
    amenities: ['Swimming Pool', 'Landscaped Garden', 'CCTV Cameras'],
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80'],
  },
  {
    id: '6',
    slug: '3br-house-ruiru-mugutha',
    title: 'Affordable 3BR House',
    type: 'sale',
    price: 13500000,
    bedrooms: 3,
    bathrooms: 3,
    location: 'Mugutha, Ruiru',
    area: 'Ruiru',
    description: 'A charming 3-bedroom house in a secure gated community.',
    features: ['Master Ensuite', 'Separate Dining', 'Fitted Wardrobes'],
    amenities: ['Gated Community', 'Ample Parking', 'Kids Play Area'],
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80'],
    badge: 'GATED COMMUNITY',
  },
  {
    id: '7',
    slug: '3br-villa-ruiru-mugutha',
    title: '3BR Villa with Gazebo',
    type: 'sale',
    price: 18500000,
    bedrooms: 3,
    bathrooms: 4,
    location: 'Mugutha, Ruiru',
    area: 'Ruiru',
    description: 'Beautiful 3-bedroom villa featuring Domestic Staff Quarters (DSQ) and an outdoor gazebo.',
    features: ['Outdoor Gazebo', 'DSQ', 'Modern Finishes'],
    amenities: ['Manicured Lawn', 'Electric Fence', 'Reliable Water'],
    images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80'],
  },
  {
    id: '8',
    slug: '4br-estate-ruiru-daykio',
    title: 'Grand 4BR Estate',
    type: 'sale',
    price: 39800000,
    bedrooms: 4,
    bathrooms: 5,
    location: 'Daykio, Ruiru',
    area: 'Ruiru',
    plotSize: '100x100',
    description: 'Massive 4-bedroom estate sitting on a 100x100 plot in the serene Daykio neighborhood.',
    features: ['Large Plot', 'Double Volume Lounge', 'Home Office'],
    amenities: ['24/7 Security', 'Paved Roads', 'Clubhouse Access'],
    images: ['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80'],
    badge: 'OWN COMPOUND',
    isFeatured: true,
  },
  {
    id: '9',
    slug: '5br-house-kasphat-kiambu',
    title: 'Spacious 5BR Family Home',
    type: 'sale',
    price: 35000000,
    bedrooms: 5,
    bathrooms: 5,
    location: 'Kasphat, Kiambu',
    area: 'Kiambu',
    description: 'Expansive 5-bedroom house ideal for a large family. Price is negotiable.',
    features: ['Multiple Living Areas', 'Ensuite Bedrooms', 'Large Kitchen'],
    amenities: ['Garden', 'Perimeter Wall', 'Ample Water Storage'],
    images: ['https://images.unsplash.com/photo-1600585154526-990dced4ea0d?w=800&q=80'],
  },
  {
    id: '10',
    slug: '4br-luxury-villa-runda',
    title: 'Luxury 4BR Runda Villa',
    type: 'sale',
    price: 88000000,
    bedrooms: 4,
    bathrooms: 5,
    location: 'Runda',
    area: 'Runda',
    description: 'Exquisite 4-bedroom villa in Runda. Available for sale at Ksh 88M or rent at Ksh 330K/mo.',
    features: ['Premium Finishes', 'Swimming Pool', 'Smart Home Features'],
    amenities: ['UN Approved Security', 'Clubhouse', 'Backup Generator'],
    images: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80'],
  },
  {
    id: '11',
    slug: '4br-villa-runda-sale',
    title: 'Contemporary 4BR Runda Villa',
    type: 'sale',
    price: 65000000,
    bedrooms: 4,
    bathrooms: 4,
    location: 'Runda',
    area: 'Runda',
    description: 'Modern 4-bedroom villa in Runda. Available for sale at Ksh 65M or rent at Ksh 450K/mo.',
    features: ['Open Concept Living', 'Large Garden', 'DSQ'],
    amenities: ['Secure Neighborhood', 'Ample Parking', 'Borehole'],
    images: ['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80'],
  },
  {
    id: '12',
    slug: '5br-luxury-lavington',
    title: '5BR Luxury Living',
    type: 'rent',
    price: 6000,
    priceCurrency: 'USD',
    priceSuffix: '/mo',
    bedrooms: 5,
    bathrooms: 6,
    location: 'Lavington',
    area: 'Lavington',
    description: 'Top-tier 5-bedroom luxury home in Lavington available for USD 6,000/mo.',
    features: ['Home Theater', 'Wine Cellar', 'Private Pool'],
    amenities: ['24/7 Concierge', 'Gym', 'Spa'],
    images: ['https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&q=80'],
    isFeatured: true,
  },
  {
    id: '13',
    slug: '4br-townhouse-lavington',
    title: '4BR Executive Townhouse',
    type: 'rent',
    price: 350000,
    priceSuffix: '/mo',
    bedrooms: 4,
    bathrooms: 5,
    location: 'Lavington',
    area: 'Lavington',
    description: 'Beautiful 4-bedroom townhouse in a serene part of Lavington.',
    features: ['Rooftop Terrace', 'Modern Kitchen', 'DSQ'],
    amenities: ['Shared Pool', 'Gym', 'Gated Security'],
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80'],
  },
  {
    id: '14',
    slug: '4br-half-acre-tigoni',
    title: '4BR Home on Half Acre',
    type: 'rent',
    price: 200000,
    priceSuffix: '/mo',
    bedrooms: 4,
    bathrooms: 4,
    location: 'Tigoni',
    area: 'Tigoni',
    plotSize: '0.5 Acres',
    description: 'Spacious 4-bedroom home sitting on a beautiful half-acre in Tigoni.',
    features: ['Tea Farm Views', 'Fireplace', 'Large Veranda'],
    amenities: ['Quiet Environment', 'Mature Garden', 'Ample Parking'],
    images: ['https://images.unsplash.com/photo-1510798831971-661eb04b3739?w=800&q=80'],
  },
  {
    id: '15',
    slug: '3br-half-acre-tigoni',
    title: 'Charming 3BR Tigoni Home',
    type: 'rent',
    price: 100000,
    priceSuffix: '/mo',
    bedrooms: 3,
    bathrooms: 3,
    location: 'Tigoni',
    area: 'Tigoni',
    plotSize: '0.5 Acres',
    description: 'Cozy 3-bedroom home on a half-acre lot offering a peaceful lifestyle.',
    features: ['Wooden Floors', 'Bright Interiors', 'Garden Space'],
    amenities: ['Secure Area', 'Water Tank', 'Pet Friendly'],
    images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80'],
  },
  {
    id: '16',
    slug: '3br-apartment-kilimani',
    title: 'Modern 3BR Apartment',
    type: 'sale',
    price: 6500000,
    bedrooms: 3,
    bathrooms: 2,
    location: 'Kilimani',
    area: 'Kilimani',
    description: 'Centrally located 3-bedroom apartment in Kilimani. Sale Ksh 6.5M or Rent Ksh 65K/mo.',
    features: ['Open Plan', 'Balcony', 'Laundry Area'],
    amenities: ['Lifts', 'Borehole', 'Security Guard'],
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80'],
  },
  {
    id: '17',
    slug: '2br-luxury-apartment-kilimani',
    title: 'Luxury 2BR Apartment',
    type: 'sale',
    price: 13800000,
    bedrooms: 2,
    bathrooms: 2,
    location: 'Kilimani',
    area: 'Kilimani',
    description: 'High-end 2-bedroom apartment. Sale Ksh 13.8M or Rent Ksh 85K/mo.',
    features: ['Fitted Kitchen', 'Ensuite Bedrooms', 'City Views'],
    amenities: ['Rooftop Pool', 'Fully Equipped Gym', 'High-Speed Lifts'],
    images: ['https://images.unsplash.com/photo-1502672260266-1c1de2d93688?w=800&q=80'],
  },
  {
    id: '18',
    slug: '3br-apartment-brookside',
    title: '3BR Brookside Apartment',
    type: 'rent',
    price: 270000,
    priceSuffix: '/mo',
    bedrooms: 3,
    bathrooms: 3,
    location: 'Brookside, Westlands',
    area: 'Westlands',
    description: 'Premium 3-bedroom apartment in the sought-after Brookside area.',
    features: ['Spacious Living', 'Modern Finishes', 'DSQ'],
    amenities: ['Swimming Pool', 'Gym', '24/7 Security'],
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80'],
  },
  {
    id: '19',
    slug: '50x100-plot-ruiru-mugutha',
    title: 'Prime 50x100 Plot',
    type: 'land',
    price: 7000000,
    bedrooms: 0,
    bathrooms: 0,
    location: 'Mugutha, Ruiru',
    area: 'Ruiru',
    plotSize: '50x100',
    description: 'A prime 50x100 plot available for sale in Ruiru Mugutha, perfect for building your dream home.',
    features: ['Ready Title Deed', 'Flat Terrain'],
    amenities: ['Water and Electricity on Site', 'Accessible Roads'],
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80'],
  },
  {
    id: '20',
    slug: 'astra-bay-lower-kabete',
    title: 'Astra Bay Studios',
    type: 'off-plan',
    price: 1960000,
    priceLabel: 'From Ksh 1.96M',
    bedrooms: 1,
    bathrooms: 1,
    location: 'Lower Kabete',
    area: 'Lower Kabete',
    description: 'Off-plan studios and apartments at Astra Bay with flexible payment plans.',
    features: ['Modern Design', 'Fitted Kitchenettes'],
    amenities: ['Gym', 'Rooftop Lounge', 'High-Speed Lifts'],
    paymentPlan: '20% deposit, balance spread over construction period',
    completionDate: 'Q4 2026',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80'],
    badge: 'PAYMENT PLAN',
    isFeatured: true,
  },
  {
    id: '21',
    slug: 'kitisuru-studios-1br',
    title: 'Kitisuru Modern Studios',
    type: 'off-plan',
    price: 2550000,
    priceLabel: 'From Ksh 2.55M',
    bedrooms: 1,
    bathrooms: 1,
    location: 'Kitisuru',
    area: 'Kitisuru',
    description: 'Off-plan studios starting from Ksh 2.55M and 1BRs from Ksh 3.64M.',
    features: ['High ROI', 'Premium Finishes'],
    amenities: ['Borehole', 'Backup Generator', 'CCTV'],
    paymentPlan: 'Flexible installments',
    completionDate: '2027',
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80'],
  },
  {
    id: '22',
    slug: 'ruaka-apartments-1br',
    title: 'Ruaka Premium 1BR',
    type: 'off-plan',
    price: 5900000,
    priceLabel: 'From Ksh 5.9M',
    bedrooms: 1,
    bathrooms: 1,
    location: 'Ruaka',
    area: 'Ruaka',
    description: 'High-quality off-plan 1BR apartments in Ruaka. 2BRs also available from Ksh 8.2M.',
    features: ['Spacious Layout', 'Balcony'],
    amenities: ['Swimming Pool', 'Gym', 'Kids Play Area'],
    paymentPlan: '30% deposit, balance over 24 months',
    completionDate: 'Q2 2026',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1de2d93688?w=800&q=80'],
  },
  {
    id: '23',
    slug: 'kihara-road-studios',
    title: 'Kihara Road Studios',
    type: 'off-plan',
    price: 1900000,
    priceLabel: 'From Ksh 1.9M',
    bedrooms: 1,
    bathrooms: 1,
    location: 'Kihara Road, Kiambu',
    area: 'Kiambu',
    description: 'Affordable off-plan studios from Ksh 1.9M and 1BRs from Ksh 4.5M.',
    features: ['Smart Use of Space', 'Modern Amenities'],
    amenities: ['Secure Parking', 'Rooftop Terrace'],
    completionDate: '2025',
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80'],
  },
  {
    id: '24',
    slug: 'kamangu-5br-maisonette',
    title: 'Kamangu 5BR Maisonette',
    type: 'off-plan',
    price: 20000000,
    priceLabel: 'Ksh 20-22M',
    bedrooms: 5,
    bathrooms: 5,
    location: 'Kamangu, Kikuyu',
    area: 'Kikuyu',
    description: 'Upcoming 5-bedroom maisonettes in Kamangu. Off-plan pricing between Ksh 20-22M.',
    features: ['All Ensuite', 'Family Room', 'Spacious Compound'],
    amenities: ['Gated Estate', 'Borehole Water', 'Paved Roads'],
    completionDate: '2027',
    images: ['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800&q=80'],
    badge: 'PAYMENT PLAN',
  }
];
